version: '3.7'
services:
  nba-statistics:
    build:
      context: ./nba-statistics
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "9890:9890"
    container_name: nba-statistics
    depends_on:
      - mysql
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

networks:
  default:
    name: test
    external: true
